# OpenAPI 3.0 Contract: Local Library Cache
# Feature: 003-local-library-cache

openapi: 3.0.3
info:
  title: MediaSage Library Cache API
  version: 1.0.0
  description: API endpoints for local library cache sync and status

paths:
  /api/library/status:
    get:
      summary: Get library cache status
      description: Returns current sync state, track count, and last sync time
      operationId: getLibraryStatus
      tags:
        - Library Cache
      responses:
        '200':
          description: Library cache status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LibraryStatusResponse'

  /api/library/sync:
    post:
      summary: Trigger library sync
      description: |
        Starts a library sync from Plex. If cache is empty, sync blocks until complete.
        If cache exists, sync runs in background. Returns immediately with started status.
      operationId: triggerLibrarySync
      tags:
        - Library Cache
      responses:
        '200':
          description: Sync started
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SyncTriggerResponse'
        '409':
          description: Sync already in progress
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    LibraryStatusResponse:
      type: object
      required:
        - track_count
        - is_syncing
      properties:
        track_count:
          type: integer
          description: Number of tracks in local cache
          example: 18432
        synced_at:
          type: string
          format: date-time
          nullable: true
          description: Timestamp of last successful sync (null if never synced)
          example: "2026-02-05T10:30:00Z"
        is_syncing:
          type: boolean
          description: Whether a sync is currently in progress
          example: false
        sync_progress:
          $ref: '#/components/schemas/SyncProgress'
        error:
          type: string
          nullable: true
          description: Error message from last failed sync (null if no error)
          example: null
        plex_connected:
          type: boolean
          description: Whether Plex server is currently reachable
          example: true

    SyncProgress:
      type: object
      nullable: true
      description: Progress details when sync is running (null when not syncing)
      properties:
        current:
          type: integer
          description: Number of tracks synced so far
          example: 5000
        total:
          type: integer
          description: Total tracks to sync
          example: 18432

    SyncTriggerResponse:
      type: object
      required:
        - started
      properties:
        started:
          type: boolean
          description: Whether sync was started
          example: true
        blocking:
          type: boolean
          description: Whether sync is blocking (first-time sync)
          example: false

    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error message
          example: "Sync already in progress"
        detail:
          type: string
          nullable: true
          description: Additional error details
